# Generated by Django 4.2.3 on 2023-07-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0002_alter_vote_slot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="weight",
            field=models.FloatField(blank=True),
        ),
    ]
