# Generated by Django 4.2.3 on 2023-07-31 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0003_alter_vote_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="slot",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votes",
                to="mainapp.slot",
            ),
        ),
    ]
